### ISSUE TITLE
selection lines are not visible

### ISSUE THREAD

**Issue by muralikodali** [neXromancers/hacksaw#26]
though selection is working and copied to clipboard, selection box is not appearing at the time selection making it difficult to know the exact area of selection.

dependencies are satisfied and i have installed hacksaw from source.

**Comment by 9ary** [comment]
What DE or WM are you running? Are you running a compositor on top of that?

**Comment by tnjd** [comment]
Have you tried using the option to set the width of the lines?

**Comment by muralikodali** [comment]
using ubuntu-mate 18.04.3 with window manager Metacity (Marco).
Marco Adavptive compositor.

**Comment by muralikodali** [comment]
i ran the command hacksaw -s 3. but no use.

**Comment by 9ary** [comment]
Try to [disable compositing](https://wiki.archlinux.org/index.php/MATE#Disabling_compositing) and see if it makes a difference. None of us uses MATE, so it's kinda hard for us to help you.

**Comment by muralikodali** [comment]
changed the option to Marco without compositing. guidelines are visible now. but it's difficult to enjoy my work without compositing.

**Comment by 9ary** [comment]
Disabling compositing is not a fix, it's a workaround. We need to figure out why this is happening.
Try [slop](https://github.com/naelstrof/slop/) with compositing enabled and `--noopengl` to see if it works. If it does then this is a bug on our side, otherwise you should report this to the MATE developers.

**Comment by muralikodali** [comment]
i have tried slop. it is working well. it has problem when i tried with --noopengl.

**Comment by 9ary** [comment]
Then this is a bug with MATE. Please file a bug report with them and link this one there.
You can tell them it's a problem with xshape. You could also try xeyes to see if that works properly.

**Comment by pickfire** [comment]
@muralikodali Try `echo $XDG_SESSION_TYPE`?
