### ISSUE TITLE
structopt as binary dependency

### ISSUE THREAD

**Issue by pickfire** [neXromancers/hacksaw#27]
`structopt` should not be needed as a dependency when using it in a library.

**Comment by tnjd** [comment]
why would someone use hacksaw as a library? not that I'm against it, I just don't see the usecase

**Comment by Lonami** [comment]
It exports a few useful abstractions over `xcb` which is otherwise a bit more painful to use and requires more knowledge.

**Comment by pickfire** [comment]
They could use hacksaw to select stuff from their application, of course one could interact through `Command`.

**Comment by tnjd** [comment]
indeed. this issue is kind of weird though since there is actually no library right now. closing for that reason, but it will be valid if/when we make hacksaw available as a library too
