### ISSUE TITLE
Getting error  when in fullscreen games or in dropdown menus: "Failed to grab cursor after 5 tries, giving up"

### ISSUE THREAD

**Issue by perdakovich** [neXromancers/hacksaw#37]
See this issue for explanation: https://github.com/naelstrof/maim/issues/283

https://github.com/neXromancers/hacksaw/assets/89806596/b4c57388-1b5e-4a9a-8563-52bdbf69d0d8

**Comment by 9ary** [comment]
Unfortunately this is not a bug, but a technical limitation. Dropdown menus and games request exclusive control of the cursor (they "grab" the cursor), but tools like hacksaw and slop (which maim uses as a library) also need to do this. Even without grabbing the cursor in hacksaw, we wouldn't be able to get any input while something else is holding a grab, so there is no way to fix this.
